<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Añadir</title>
</head>
<body>


</form>
    <h2>Añadir</h2>
    <form action="index.php?añadir" method="post">
        <input type="text" name="title" placeholder="Titulo"/>
        <input type="text" name="fecha" placeholder="fecha"/>
        <input type="submit" name="añadir" value="Añadir"/>
    </form>

    
</body>
</html>