<!DOCTYPE html>
<html>
	<head>
		<title>Blog</title>
		<link rel="stylesheet" href="views/style.css" type="text/css">
	</head>
	<body>
		<header>
			<h1>Blog</h1>
			<nav>
				<ul>
					<li><a href="index.php">Inicio</a></li>
					<?php
					if($_SESSION['user'] -> getName()=="")
						echo '<li><a href="index.php?login">Login</a></li>';
					else 
						// echo 'Hola '.$_SESSION['user']->getName().' 
						echo '<li><a href="index.php?login&logout">Salir</a></li>'.'
						<li><a href="index.php?añadir">Añadir</a></li>';
					?>
				</ul>
			</nav>
		</header>
		<section>
			<ul>

			</ul>
		</section>
	</body>
</html>