<!DOCTYPE html>
<html>
<head>
	<title>Mi blog</title>
</head>
<body>
<h1>Mi blog</h1>
<a href="index.php">Inicio</a> -

<?php
if($_SESSION['user']->getName()=="")
	echo '<a href="index.php?login">Login</a>';
else 
	echo 'Hola '.$_SESSION['user']->getName().' 
	<a href="index.php?login&logout">Salir</a>';

echo "<br>";
	foreach($articles as $article){
		echo "<h1>".$article->getTitle()."</h1>";
		echo "<p>Autor: ".$article->getAuthor()->getName().". Fecha: ".$article->getDatetime()."</p>";
		echo "<p>".$article->getText()."</p>";
		if($article->getImage()) echo '<img src="views/images/'.$article->getImage().'" width="100px"/>';

		foreach($article->getComments() as $comment){
			echo "<br>".$comment->getAuthor()->getName()." dijo (".$comment->getDatetime()."): ".$comment->getText();
		}

	}
?>
<br><br><h2>Nuevo articulo</h2>
<form action="index.php?article" method="POST" enctype="multipart/form-data">
	Titulo: <input type="text" name="title"/><br>
	Texto: <input type="text" name="text"/><br>
	Imagen: <input type="file" name="image"/><br>
	<input type="submit" name="new" value="Subir articulo"/>
</form>


</body>
</html>