<!DOCTYPE html>
<html>
	<head>
		<title>Blog</title>
		<link rel="stylesheet" href="views/css/style.css">
	</head>
	<body>
	<header>
		<h1>Blog</h1>
		<nav>
			<ul>
				<li><a href="index.php">Inicio</a></li>
				<?php
				if($_SESSION['user'] -> getName()=="")
					echo '<li><a href="index.php?login">Login</a></li>';
				else if ($_SESSION['user'] -> getId_rol() == 1) {
					echo '<li><a href="index.php?login&logout">Salir</a></li>';
				} else {
					// echo 'Hola '.$_SESSION['user']->getName();
					echo '<li><a href="index.php?login&logout">Salir</a></li>'.'
					<li><a href="index.php?añadir">Articulos</a></li>
					<li><a href="index.php?admin">Administracion</a></li>';
				}
				?>
			</ul>
		</nav>
	</header>
	<section>
		<?php
		echo '<div id="blog">';
		foreach($articulos as $Articulo) {
			// echo "<li>".$Articulo->getTitle()." - ".$Articulo->getContenido()." - ".$Articulo->getFecha()." - ".$Articulo->getImagen()." - ".$Articulo->getId_user()."</li>";
			echo '<div id="articulo"><h2>'.$Articulo->getTitle().'</h2> <br>';
			echo '<p>'.$Articulo->getContenido(). '</p><br>';
			if($Articulo->getImagen()) {
				echo '<img src="views/images/'.$Articulo->getImagen().'" width="50%"/>';
			}
			echo '<div id="fecha"><p> Fecha: '.$Articulo->getFecha().'</p>';
			echo '<p> Autor: '.$Articulo->getId_user()->getName().'</p>';

			// var_dump($Articulo->getComentarios());
			foreach ($Articulo->getComentarios() as $comentario) {
				var_dump($comentario);
				echo '<h2>Comentarios</h2> <br>';
				echo '<p>'.$comentario->getId_user()->getName().'</p><br>';
				echo '<p>'.$comentario->getComentario().'</p><br>';
				echo '<p>'.$comentario->getFecha().'</p><br>';
			}
			echo '</div></div>';
			if ($_SESSION['user'] -> getName() != "") {
				echo '<div id="formComentar"><form action="index.php?comentario&id_articulo='.$Articulo->getId().'" method="post">
					<label>Comentario: </label><br>
					<textarea name="comentario" placesholder="comentario..."></textarea>
					<input type="submit" name="comentar" value="Comentar"/>
				</form></div>';
			}
		}
		echo '</div>';
		?>
	</section>
	</body>
</html>